# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    
    - name: Cache node_modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: build-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: build-node_modules-

    - run: npm i

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: ['test', 'test:nestjs', 'test:mocha']
    if: contains(github.event.head_commit.modified, 'example-application/') || contains(github.event.head_commit.modified, 'graphics/') || contains(github.event.head_commit.modified, 'recipes/')
    
    steps:
    - uses: actions/checkout@v2

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
    
    - name: Cache node_modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: build-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: build-node_modules-

    - run: npm i

    - run: npm run ${{ matrix.test-type }}
